### ISSUE TITLE
[bug] not load

### ISSUE THREAD

**Issue by Blskk** [nulli0n/SunLight-spigot#16]
paper1.20.1 

```
[15:44:51 INFO]: [PartyAndFriendsGUI] Disabling PartyAndFriendsGUI v1.0.240-E
[15:44:51 INFO]: [SunLight] Disabling SunLight v3.9.1
[15:44:51 ERROR]: Error occurred (in the plugin loader) while disabling SunLight v3.9.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'void su.nexmedia.engine.command.CommandManager.unregisterCommand(su.nexmedia.engine.api.command.GeneralCommand)'
        at su.nightexpress.sunlight.command.CommandRegulator.lambda$onShutdown$41(CommandRegulator.java:99) ~[SunLight-3.9.1【基础】.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at su.nightexpress.sunlight.command.CommandRegulator.onShutdown(CommandRegulator.java:95) ~[SunLight-3.9.1【基础】.jar:?]
        at su.nexmedia.engine.api.manager.AbstractManager.shutdown(AbstractManager.java:28) ~[NexEngine【基础前置】.jar:?]
        at su.nightexpress.sunlight.SunLight.disable(SunLight.java:79) ~[SunLight-3.9.1【基础】.jar:?]
        at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:237) ~[NexEngine【基础前置】.jar:?]
        at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:98) ~[NexEngine【基础前置】.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-60]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[paper-1.20.1.jar:git-Paper-60]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.20.1.jar:git-Paper-60]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.disablePlugins(CraftServer.java:567) ~[paper-1.20.1.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.20.1.jar:git-Paper-60]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:806) ~[paper-1.20.1.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1210) ~[paper-1.20.1.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-60]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:44:51 INFO]: [SunLight_Economy] Disabling SunLight_Economy v1.2.0
[15:44:51 INFO]: [SunLight_Economy] Auto-save: Saved 0 online users | 0 offline users.
```

**Comment by Blskk** [comment]
Under the same conditions, I restarted the paper several times and suddenly it became usable

**Comment by Blskk** [comment]
Under the same conditions, I restarted the paper several times and suddenly it became usable
