### ISSUE TITLE
Running Purpur 1.20.1 (build 2014), latest NexEngine, latest SunLight. Have an issue:

### ISSUE THREAD

**Issue by ghost** [nulli0n/SunLight-spigot#17]
```
[09:53:14 ERROR]: Error occurred (in the plugin loader) while disabling SunLight v3.9.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'void su.nexmedia.engine.command.CommandManager.unregisterCommand(su.nexmedia.engine.api.command.GeneralCommand)'
	at su.nightexpress.sunlight.command.CommandRegulator.lambda$onShutdown$41(CommandRegulator.java:99) ~[SunLight-3.9.1.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at su.nightexpress.sunlight.command.CommandRegulator.onShutdown(CommandRegulator.java:95) ~[SunLight-3.9.1.jar:?]
	at su.nexmedia.engine.api.manager.AbstractManager.shutdown(AbstractManager.java:28) ~[NexEngine (1).jar:?]
	at su.nightexpress.sunlight.SunLight.disable(SunLight.java:79) ~[SunLight-3.9.1.jar:?]
	at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:237) ~[NexEngine (1).jar:?]
	at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:98) ~[NexEngine (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.disablePlugins(CraftServer.java:584) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:956) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:846) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1237) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nulli0n** [comment]
Fixed in latest updates.
