### ISSUE TITLE
[Feature Request] Disable chat channels functionality.

### ISSUE THREAD

**Issue by thunder-red-star** [nulli0n/SunLight-spigot#21]
This is an awesome plugin, but I'd like to disable the chat channels functionality as I have another plugin that handles chat functions. 

For now I've "disabled" it by just erasing all the contents of channels.yml, but I'd prefer a more explicit method that doesn't throw an error into console every time someone chats.

⬇️

```
java.lang.NullPointerException: Cannot invoke "su.nightexpress.sunlight.module.chat.ChatChannel.getId()" because "channel" is null
        at su.nightexpress.sunlight.module.chat.ChatModule.isInChannel(ChatModule.java:227) ~[SunLight-3.9.4.jar:?]
        at su.nightexpress.sunlight.module.chat.ChatModule.handleChatEvent(ChatModule.java:312) ~[SunLight-3.9.4.jar:?]
        at su.nightexpress.sunlight.module.chat.listener.ChatListener.onChatProcessMessageHigh(ChatListener.java:69) ~[SunLight-3.9.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor380.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2028]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2028]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2028]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[purpur-1.20.1.jar:git-Purpur-2028]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[purpur-1.20.1.jar:git-Purpur-2028]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2541) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2691) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$18(ServerGamePacketListenerImpl.java:2369) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nulli0n** [comment]
Disable chat module in the config.yml instead.
