### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1753449579** [nulli0n/SunLight-spigot#41]
Error occurred while disabling SunLight v3.9.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "su.nexmedia.engine.api.data.AbstractUserManager.shutdown()" because the return value of "su.nexmedia.engine.api.data.UserDataHolder.getUserManager()" is null
        at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:236) ~[?:?]
        at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:84) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349) ~[forge-1.20.1-47.2.17-universal.jar%23197!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:365) ~[forge-1.20.1-47.2.17-universal.jar%23197!/:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:507) ~[forge-1.20.1-47.2.17-universal.jar%23197!/:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:209) ~[?:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:78) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.17-universal.jar%23197!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.17-universal.jar%23197!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.17-universal.jar%23197!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.17-universal.jar%23197!/:997de31d-ddc9a2dad-d2eba2c8-47.2.17]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.17-universal.jar%23197!/:997de31d-ddc9a2dad-d2eba2c8-47.2.17]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23192!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by nulli0n** [comment]
Modded servers are not supported.
