### ISSUE TITLE
SunLight isn't working, although SunLight_Economy is working

### ISSUE THREAD

**Issue by Cubichesky** [nulli0n/SunLight-spigot#5]
[21:43:04 ERROR]: Error occurred while enabling SunLight v3.4.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketAdapter
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at su.nightexpress.sunlight.modules.chat.ChatManager.onLoad(ChatManager.java:117) ~[SunLight-3.4.5.jar:?]
        at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:21) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.module.AbstractModule.setup(AbstractModule.java:29) ~[NexEngine.jar:?]
        at su.nightexpress.sunlight.modules.SunModule.setup(SunModule.java:21) ~[SunLight-3.4.5.jar:?]
        at su.nexmedia.engine.api.module.AbstractModuleManager.register(AbstractModuleManager.java:55) ~[NexEngine.jar:?]
        at su.nightexpress.sunlight.modules.ModuleManager.loadModules(ModuleManager.java:49) ~[SunLight-3.4.5.jar:?]
        at su.nightexpress.sunlight.SunLight.enable(SunLight.java:83) ~[SunLight-3.4.5.jar:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:221) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:92) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1933]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketAdapter
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 29 more
[21:43:04 INFO]: [SunLight] Disabling SunLight v3.4.5

**Comment by nulli0n** [comment]
Update ProtocolLib

**Comment by Cubichesky** [comment]
> Update ProtocolLib

it is updated, but does not work. I tried different versions of ProtocolLib, but it didn't work anywhere. Only the errors in the console were changed. Version 1.19.3. Core PurPur -1.19.3-1933
![изображение](https://user-images.githubusercontent.com/66108320/227750753-61339d0e-8de2-498c-b994-c9a709d01fb2.png)

**Comment by Cubichesky** [comment]
Okay, I fixed it. Changed Java 20 to Java 18
