### ISSUE TITLE
SCOREBOARD_OBJECTIVE packet has incorrect RenderType

### ISSUE THREAD

**Issue by diogotcorreia** [nulli0n/SunLight-spigot#62]
Hey,
My plugin ([Triton](https://github.com/tritonmc/Triton/)) is also using ProtocolLib and while intercepting a packet created by SunLight it's throwing an exception:

```
[15:46:33 ERROR]: [Triton] Unhandled exception number 1024 occurred in onAsyncPacket() for Triton
java.lang.IllegalArgumentException: No enum constant com.comphenix.protocol.wrappers.EnumWrappers.RenderType.
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.craftbukkit.legacy.FieldRename.valueOf(FieldRename.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at ProtocolLib.jar/com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_legacy_FieldRename_valueOf(EnumWrappers.java) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:1104) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:1090) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:303) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.reflect.StructureModifier.readSafely(StructureModifier.java:277) ~[ProtocolLib.jar:?]
        at com.rexcantor64.triton.spigot.packetinterceptor.ProtocolLibListener.handleScoreboardObjective(ProtocolLibListener.java:713) ~[?:?]
        at com.rexcantor64.triton.spigot.packetinterceptor.ProtocolLibListener.onPacketSending(ProtocolLibListener.java:789) ~[?:?]
        at ProtocolLib.jar/com.comphenix.protocol.async.AsyncListenerHandler.lambda$processPacket$4(AsyncListenerHandler.java:602) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:600) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:572) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.async.AsyncListenerHandler.access$100(AsyncListenerHandler.java:48) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.async.AsyncListenerHandler$1.run(AsyncListenerHandler.java:217) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.async.AsyncListenerHandler.lambda$start$1(AsyncListenerHandler.java:286) ~[ProtocolLib.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Upon some debugging, it appears that SunLight is the cause of this issue, because it's relying on ProtocolLib's defaults (which admittedly should be better :sweat_smile:) instead of forcing the value of `RenderType`.

An easy fix would be to add

```java
objectivePacket.getRenderTypes().write(0, EnumWrappers.RenderType.INTEGER);
```

to

https://github.com/nulli0n/SunLight-spigot/blob/b1b656d190bc989fdbbf7e8a5153a8f583655a35/Core/src/main/java/su/nightexpress/sunlight/module/scoreboard/impl/Board.java#L76-L89

This would basically yield the same packet at the network level, but the enum value would be working correctly.

**Comment by nulli0n** [comment]
Done
