### ISSUE TITLE
Failed to load at startup

### ISSUE THREAD

**Issue by Moyuyanli** [nulli0n/SunLight-spigot#77]
我在启动的时候加载插件失败，报错如下：
```java
[01:42:36] [Server thread/INFO]: [SunLight] Enabling SunLight v3.12.3
[01:42:36] [Server thread/INFO]: [SunLight] Powered by nightcore
[01:42:36] [Server thread/WARN]: [SunLight] ===================================
[01:42:36] [Server thread/WARN]: [SunLight] WARNING: You're running an outdated/deprecated server version (1.18.2)!
[01:42:36] [Server thread/WARN]: [SunLight] Support for this version will be dropped soon.
[01:42:36] [Server thread/WARN]: [SunLight] Please, upgrade your server to at least 1.19.4.
[01:42:36] [Server thread/WARN]: [SunLight] ===================================
[01:42:36] [Server thread/INFO]: [SunLight] Read database configuration...
[01:42:36] [Server thread/WARN]: [SunLight] Locale file for 'zh' language not found. Using default 'en' locale.
[01:42:36] [Server thread/ERROR]: Error occurred while enabling SunLight v3.12.3 (Is it up to date?)
 java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariConfig
        at su.nightexpress.nightcore.database.AbstractConnector.<init>(AbstractConnector.java:22) ~[?:?]
        at su.nightexpress.nightcore.database.connection.SQLiteConnector.<init>(SQLiteConnector.java:11) ~[?:?]
        at su.nightexpress.nightcore.database.AbstractConnector.create(AbstractConnector.java:33) ~[?:?]
        at su.nightexpress.nightcore.database.AbstractDataHandler.<init>(AbstractDataHandler.java:40) ~[?:?]
        at su.nightexpress.nightcore.database.AbstractUserDataHandler.<init>(AbstractUserDataHandler.java:41) ~[?:?]
        at su.nightexpress.nightcore.database.AbstractUserDataHandler.<init>(AbstractUserDataHandler.java:37) ~[?:?]
        at su.nightexpress.sunlight.data.DataHandler.<init>(DataHandler.java:65) ~[?:?]
        at su.nightexpress.sunlight.SunLightPlugin.enable(SunLightPlugin.java:60) ~[?:?]
        at su.nightexpress.nightcore.NightPlugin.loadManagers(NightPlugin.java:150) ~[?:?]
        at su.nightexpress.nightcore.NightDataPlugin.loadManagers(NightDataPlugin.java:12) ~[?:?]
        at su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:56) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:424) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:1.18.2-6b922eb6]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:350) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:1.18.2-6b922eb6]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:531) ~[server-1.18.2-20220404.173914-srg.jar%2355!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:404) ~[server-1.18.2-20220404.173914-srg.jar%2355!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:240) ~[server-1.18.2-20220404.173914-srg.jar%2355!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:945) ~[server-1.18.2-20220404.173914-srg.jar%2355!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:344) ~[server-1.18.2-20220404.173914-srg.jar%2355!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariConfig
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:191) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:132) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 22 more
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariConfig
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-1.0.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-1.0.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:189) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:132) ~[forge-1.18.2-40.2.18-universal.jar%2360!/:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 22 more
```
The specific reason is that HikariCP cannot be found

The core I'm using is catServer

Java version: Zulu 21

The pre-plugin uses: nightcore-2.6.3

**Comment by Moyuyanli** [comment]
我尝试手动将 HikariCP  添加到libraries，但是结果依然是失败。

**Comment by Moyuyanli** [comment]
I'm sorry to trouble you. The plug-in supported by my terminal is bukkit.

**Comment by Moyuyanli** [comment]
Can't handle it?
Then I want to ask if it's a server-side problem on my side, or a plugin incompatibility problem?

**Comment by nulli0n** [comment]
Please read manual
![изображение](https://github.com/user-attachments/assets/07ee26a9-856d-4d17-ba25-874fe19f5d7a)
